# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: db
  host: 127.0.0.1
  username: root

development:
  primary:
    <<: *default
  follower:
    <<: *default
    replica: true
